server:
  port: 12008

spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/

  thymeleaf:
    mode: HTML

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 120.25.254.155:9300

  rabbitmq:
    host: 120.25.254.155
    username:
    password:
    virtual-host:
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: inori.search.exchange
    publisher-confirms: true

  redis:
    hostname: 120.25.254.155
    maxTotal: 20
    testOnBorrow: true
    maxIdle: 10
    maxWaitMillis: 5
    timeout: 2000

  datasource:
    url: jdbc:mysql://120.25.254.155:3306/db_blog?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:/**/*Mapper.xml
  typeAliasesPackage: inori.blog.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapUnderscoreToCamelCase: true
    cache-enabled: true

inori:
  token:
    tokenPrefix:
  oss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    httpBase:
    bucket:

log:
  path: blog-logs